spring:
  application:
   name: consumer
  kafka:
    consumer:
      group-id: myGroup
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.JasonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
server:
  port: 8020
